from django.urls import path

from .views import (
    book_class,
    cancel_booking,
    analyze_meal_photo,
    class_list,
    create_meal,
    create_workout,
    delete_workout,
    health_check,
    request_password_reset,
    reset_password,
    sign_in,
    sign_up,
    social_auth,
    user_bookings,
    user_detail,
    user_list,
    user_meals,
    user_workouts,
)

urlpatterns = [
    path('health/', health_check, name='health-check'),
    path('users/', user_list, name='user-list'),
    path('users/<int:user_id>/', user_detail, name='user-detail'),
    path('users/<int:user_id>/bookings/', user_bookings, name='user-bookings'),
    path('users/<int:user_id>/workouts/', user_workouts, name='user-workouts'),
    path('users/<int:user_id>/meals/', user_meals, name='user-meals'),
    path('classes/', class_list, name='class-list'),
    path('classes/<int:class_id>/book/', book_class, name='book-class'),
    path('bookings/<int:booking_id>/cancel/', cancel_booking, name='cancel-booking'),
    path('workouts/', create_workout, name='create-workout'),
    path('workouts/delete/', delete_workout, name='delete-workout-post'),
    path('workouts/<int:workout_id>/', delete_workout, name='delete-workout'),
    path('workouts/<str:workout_id>/', delete_workout, name='delete-workout-invalid-id'),
    path('meals/', create_meal, name='create-meal'),
    path('meals/analyze/', analyze_meal_photo, name='analyze-meal-photo'),
    path('auth/signup/', sign_up, name='sign-up'),
    path('auth/signin/', sign_in, name='sign-in'),
    path('auth/social/', social_auth, name='social-auth'),
    path('auth/request-password-reset/', request_password_reset, name='request-password-reset'),
    path('auth/reset-password/', reset_password, name='reset-password'),
]
