from django.urls import path

from .views import (
    ai_assistant_chat,
    book_class,
    cancel_booking,
    analyze_meal_photo,
    class_list,
    create_meal,
    create_workout,
    delete_meal,
    delete_personal_record,
    delete_workout,
    exercise_list,
    health_check,
    request_password_reset,
    reset_password,
    review_trainer_application,
    sign_in,
    sign_out,
    sign_up,
    social_auth,
    stripe_webhook,
    trainer_applications,
    trainer_chat_conversations,
    trainer_chat_message,
    update_meal,
    user_bookings,
    user_ai_chat_messages,
    user_trainer_chat_messages,
    user_detail,
    user_list,
    user_meals,
    user_personal_records,
    user_workouts,
    create_personal_record,
)

urlpatterns = [
    path('health/', health_check, name='health-check'),
    path('stripe/webhook/', stripe_webhook, name='stripe-webhook'),
    path('ai-assistant/chat/', ai_assistant_chat, name='ai-assistant-chat'),
    path('users/', user_list, name='user-list'),
    path('users/<int:user_id>/', user_detail, name='user-detail'),
    path('users/<int:user_id>/ai-messages/', user_ai_chat_messages, name='user-ai-chat-messages'),
    path('users/<int:user_id>/trainer-messages/', user_trainer_chat_messages, name='user-trainer-chat-messages'),
    path('users/<int:user_id>/bookings/', user_bookings, name='user-bookings'),
    path('users/<int:user_id>/workouts/', user_workouts, name='user-workouts'),
    path('users/<int:user_id>/meals/', user_meals, name='user-meals'),
    path('users/<int:user_id>/personal-records/', user_personal_records, name='user-personal-records'),
    path('exercises/', exercise_list, name='exercise-list'),
    path('personal-records/', create_personal_record, name='create-personal-record'),
    path('personal-records/delete/', delete_personal_record, name='delete-personal-record-post'),
    path('personal-records/<int:record_id>/', delete_personal_record, name='delete-personal-record'),
    path('classes/', class_list, name='class-list'),
    path('trainer-applications/', trainer_applications, name='trainer-applications'),
    path('trainer-applications/<int:application_id>/review/', review_trainer_application, name='review-trainer-application'),
    path('trainer-chat/conversations/', trainer_chat_conversations, name='trainer-chat-conversations'),
    path('trainer-chat/messages/', trainer_chat_message, name='trainer-chat-message'),
    path('classes/<int:class_id>/book/', book_class, name='book-class'),
    path('bookings/<int:booking_id>/cancel/', cancel_booking, name='cancel-booking'),
    path('workouts/', create_workout, name='create-workout'),
    path('workouts/delete/', delete_workout, name='delete-workout-post'),
    path('workouts/<int:workout_id>/', delete_workout, name='delete-workout'),
    path('workouts/<str:workout_id>/', delete_workout, name='delete-workout-invalid-id'),
    path('meals/', create_meal, name='create-meal'),
    path('meals/analyze/', analyze_meal_photo, name='analyze-meal-photo'),
    path('meals/update/', update_meal, name='update-meal-post'),
    path('meals/delete/', delete_meal, name='delete-meal-post'),
    path('meals/<int:meal_id>/update/', update_meal, name='update-meal'),
    path('meals/<int:meal_id>/', delete_meal, name='delete-meal'),
    path('meals/<str:meal_id>/', delete_meal, name='delete-meal-invalid-id'),
    path('auth/signup/', sign_up, name='sign-up'),
    path('auth/signin/', sign_in, name='sign-in'),
    path('auth/signout/', sign_out, name='sign-out'),
    path('auth/social/', social_auth, name='social-auth'),
    path('auth/request-password-reset/', request_password_reset, name='request-password-reset'),
    path('auth/reset-password/', reset_password, name='reset-password'),
]
