# Generated by Django 4.2.30 on 2026-05-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=150)),
                ('room', models.CharField(max_length=100)),
                ('schedule_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('fitness_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='api.fitnessclass')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'class_bookings',
                'ordering': ['-booked_at'],
                'unique_together': {('user', 'fitness_class')},
            },
        ),
    ]
