# Generated by Django 4.2.30 on 2026-05-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fitnessclass_classbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='slots',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
