# Generated by Django 4.2.30 on 2026-05-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fitnessclass_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('low', 'Gentle / Restorative'), ('moderate', 'Moderate / Flow'), ('high', 'High / Peak Power')], max_length=30)),
                ('calories_burned', models.PositiveIntegerField()),
                ('workout_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['-workout_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=150)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(db_column='workout_id', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workout')),
            ],
            options={
                'db_table': 'workout_exercises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fats_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-meal_date'],
            },
        ),
    ]
